### ISSUE TITLE
Unmounted pool causes  500 - Internal Server Error on filesystems section

### ISSUE THREAD

**Issue by thenebular** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#2]
If I manually unmount the mergerfs pool or the pool is prevented from mounting for some reason (like a missing disk for instance) the file system section of the OMV web GUI will no longer display any file system information at all. It only gives the error:
 500 - Internal Server Error
Couldn't extract an UUID from the provided path "path-to-mergerfs-pool"

**Comment by ryecoaaron** [comment]
Give 6.3.4 a try.  In the repo now.

**Comment by thenebular** [comment]
Issue has been resolved

Thank you.
