### ISSUE TITLE
No Permission on Absolute Path as User

### ISSUE THREAD

**Issue by kilo-WATT** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#3]
I have successfully created a MergerFS pool with my 8 HDD. However, since switching to OMV6, I am running into a permissions issue when trying to access the root folder of said pool. In this case, I named the pool "storage."

When I explore the files with `ls -la /srv/mergerfs/storage` I am presented with the following:

`ls: cannot access '/srv/mergerfs/storage': Permission denied`
`total 8`
`drwxrwxrwx  3 root root 4096 Feb 20 21:24 .`
`drwxr-xr-x 16 root root 4096 Feb 20 21:24 ..`
`d?????????  ? ?    ?       ?            ? storage`

However, if I use sudo in front of that command results in the following which is what you expect:
`drwxrwxrwx  3 root  root  4096 Feb 20 21:24 .`
`drwxr-xr-x 16 root  root  4096 Feb 20 21:24 ..`
`drwxrwsrwx  4 root root 4096 Feb 20 21:45 storage`

I have tried doing chown on /srv/mergerfs/storage to the user and users group with no success. Have never had a problem with mergerFS on other linux distros and OMV4 (from which I am upgrading from).

**Comment by ryecoaaron** [comment]
What are your options for the pool?  Seems like allow_other isn't in there.

**Comment by kilo-WATT** [comment]
That was it. Must have pasted some of the extra options right over top of the defaults entered and didn't notice it. Re-adding those and restarting solved the problem. Thanks!

**Comment by ryecoaaron** [comment]
Glad it is was simple.  In future versions of mergerfs (not the plugin), allow_other will always be added avoiding this.
