### ISSUE TITLE
Passthrough snapshot to backend

### ISSUE THREAD

**Issue by Max-Sum** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#4]
I currently run 3 BtrFS backends. And I couldn't get snapshot management through dashboard.
I think it's possible to implement snapshot when all the backends of mergerfs supports snapshots. So that user could manage snapshot just like using a single BtrFS.

**Comment by ryecoaaron** [comment]
are you referring to manually created snapshots?  For auto created snapshots, I would just scheduled the snapshot creation at the same time for all three backends.

**Comment by Max-Sum** [comment]
Currently I am using snapper to do snapshots. But it could be eaiser to manage if I could list out snapshot on WebUI and do manual snapshots through the “snapshot” button in “filesystem” page.

**Comment by ryecoaaron** [comment]
OMV has snapshot functionality in the shared folder tab.  You can schedule snaps as well.  If you want the whole disk, create a shared folder of the whole disk.  The plugin can't add anything to the filesystem tab.
