### ISSUE TITLE
exclude Snapraid files when rebalancing/deduplicating

### ISSUE THREAD

**Issue by molnarti** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#5]
In order to provide a better integrated experience, i suggest that the mergerfs plugin automatically excludes the content files created by snapraid from the deduplication and balance jobs.

**Comment by ryecoaaron** [comment]
Fixed in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfs/commit/efb2ef9f3093ce4a79c383c8496b826963d03122  I will release an update when I get a chance.
