### ISSUE TITLE
When partition is referenced in merge fs it should show that it is referenced under file systems

### ISSUE THREAD

**Issue by trajano** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#6]
Just to improve the UI

If I were to reference a partition in mergefs the `/storage/filesystems` list should mark it as referenced.

**Comment by ryecoaaron** [comment]
If you create a sharedfolder on the mergerfs pool, it will show as referenced.  It will not show a filesystem in the pool as referenced since there is no sharedfolder referencing it directly.  The plugin can't change this.

**Comment by ryecoaaron** [comment]
You could just add a sharedfolder (that you don't use) to the filesystem(s) in the pool if you want it to be marked as referenced.
