### ISSUE TITLE
Upgrade for OMV 7

### ISSUE THREAD

**Issue by m3Lith** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#7]
Was about to upgrade to OMV 7, but noticed that this plugin does not have a version for it: https://wiki.omv-extras.org/doku.php?id=omv7:omv7_plugins:omv-extras

**Comment by ryecoaaron** [comment]
You can use the OMV 6 version since the plugin hasn't changed - https://wiki.omv-extras.org/doku.php?id=omv6:omv6_plugins:mergerfs
